mp.openapi.extensions.smallrye.info.title=Automatiko Engine :: Maven Archetypes :: Service
mp.openapi.extensions.smallrye.info.version=0.35.0
mp.openapi.extensions.smallrye.info.description=Automatiko Service Archetype

quarkus.swagger-ui.theme=newspaper
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.title=Automatiko Engine :: Maven Archetypes :: Service API
quarkus.swagger-ui.footer=Powered by Automatiko
