spring.datasource.url: jdbc:h2:file:./flowable-db

# Flowable-Engine
flowable:
  external:
    worker:
      rest:
        base-url: http://localhost:8080
        authentication:
          basic:
            username: admin
            password: test
      polling-interval: 10000 # 10 seconds
