spring.datasource.url: jdbc:h2:file:./camunda7-db

# Camunda-Engine
camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter:
    create: All
  deployment-resource-pattern:
    - "*.bpmn"
    - "*.dmn"
    - "*.form"
  generic-properties:
    properties:
      initializeTelemetry: false
      telemetryReporterActivate: false

## External-Task-Client
  client:
    base-url: http://localhost:8080/engine-rest
    lock-duration: 10000
    async-response-timeout: 20000
    worker-id: ${random.uuid}
